CLASS zcl_lab_03_contract_dnavas DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_03_contract_dnavas IMPLEMENTATION.
ENDCLASS.
