CLASS zcl_lab_08_work_record_dnavas DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_08_work_record_dnavas IMPLEMENTATION.
ENDCLASS.
